# Generated by Django 6.0 on 2026-03-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('jamb_cutoff', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('required_subjects', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='programmes__is_acti_eb96cf_idx')],
            },
        ),
    ]
