# Generated by Django 6.0 on 2026-03-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.IntegerField()),
                ('jamb_component', models.IntegerField()),
                ('olevel_component', models.IntegerField()),
                ('sitting_component', models.IntegerField()),
                ('recency_component', models.IntegerField()),
                ('qualified', models.BooleanField()),
                ('confidence', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('disqualified', 'Disqualified')], max_length=32)),
                ('recommendation', models.CharField(choices=[('admit', 'Admit'), ('review', 'Review'), ('reject', 'Reject')], max_length=32)),
                ('reasoning', models.TextField()),
                ('factors_used', models.JSONField(default=list)),
                ('bias_flag', models.BooleanField(default=False)),
                ('bias_explanation', models.TextField(blank=True, null=True)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_decision', to='applications.studentapplication')),
            ],
            options={
                'indexes': [models.Index(fields=['qualified'], name='screening_a_qualifi_ceb614_idx'), models.Index(fields=['recommendation'], name='screening_a_recomme_2ae33f_idx')],
            },
        ),
    ]
