# Generated by Django 4.2.29 on 2026-03-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsdecision',
            name='audit_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admissionsdecision',
            name='audit_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionsdecision',
            name='chain_of_thought',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='admissionsdecision',
            name='identified_risks',
            field=models.JSONField(default=list),
        ),
    ]
