# Generated by Django 6.0 on 2026-03-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, db_index=True, default='', max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('state_of_origin', models.CharField(max_length=128)),
                ('jamb_score', models.IntegerField()),
                ('olevel_results', models.JSONField(default=list)),
                ('number_of_sittings', models.IntegerField(choices=[(1, 'One sitting'), (2, 'Two sittings')])),
                ('result_year', models.IntegerField()),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('screened', 'Screened'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('review', 'Review')], db_index=True, default='pending', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='programmes.programme')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='application_status_80933b_idx'), models.Index(fields=['programme'], name='application_program_da26e0_idx'), models.Index(fields=['submitted_at'], name='application_submitt_184147_idx')],
            },
        ),
    ]
