# Generated by Django 4.2.29 on 2026-03-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='document_upload',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='id_upload',
            field=models.FileField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='transcript_upload',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
    ]
