# Generated by Django 6.0 on 2026-03-25 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('admitted', 'Admitted'), ('rejected', 'Rejected'), ('review', 'Review')], max_length=32)),
                ('ai_recommendation', models.CharField(max_length=32)),
                ('ai_score', models.IntegerField()),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('is_override', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='applications.studentapplication')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['decided_at'], name='audit_audit_decided_138fd9_idx'), models.Index(fields=['is_override'], name='audit_audit_is_over_375bc7_idx')],
            },
        ),
    ]
